version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "content-studio-team"
    assignees:
      - "content-studio-team"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "content-studio-team"
    assignees:
      - "content-studio-team"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "content-studio-team"
    assignees:
      - "content-studio-team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
